### ISSUE TITLE
Poor visibility of Navbar / header 

### ISSUE THREAD

**Issue by shivaylamba** [dA505819/dA505819.github.io#4]
![image](https://user-images.githubusercontent.com/19529592/78276253-62853b00-7530-11ea-9bf8-31314721fdac.png)

**Comment by shivaylamba** [comment]
@dA505819

**Comment by dA505819** [comment]
@shivaylamba Thankyou for raising this issue. To be precise, I am finding ways to improve it further.
If you can help in it or suggest some ways, it would be a pleasure.

**Comment by shivaylamba** [comment]
Sure, so I think you should use a header with a background and a fixed div.

**Comment by dA505819** [comment]
I have tried things but still they don't work.
If you can generate a PR, I will definitely merge.

**Comment by shivaylamba** [comment]
Okay

**Comment by dA505819** [comment]
Thankyou!
